name: ST Release Workflow Replica

on: 
    workflow_dispatch:
     inputs:
      ReleaseMode:
        description: ga,beta,alpha
        required: false
      buildNumber:
        description: the buildnumber used only for beta
        required: false


jobs:
  build:
    runs-on: st-win
    steps: 
    - name: Checkout
      uses: actions/checkout@v2.3.3
