# This is a basic workflow to help you get started with Actions

name: Output Demo

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.step1.outputs.test}}
      output2: ${{ steps.step2.outputs.test}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
